apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eddy-kafka-graphql-bridge.fullname" . }}-config
data:
  BEHIND_PROXY: {{ .Values.behindProxy | quote }}
  BOOTSTRAP_SERVER: {{ tpl .Values.kafkaBootstrapServer . | quote }}
  DEBUG: {{ .Values.debug | quote }}
  JWT_ALGORITHM: {{ .Values.jwtAlgorithm | quote }}
  JWT_KEY: {{ .Values.jwtKey | quote }}
  JWT_PREFIX: {{ .Values.jwtPrefix | quote }}
  JWT_USER_FIELD: {{ .Values.jwtUserField | quote }}
  METRICS: {{ .Values.metrics | quote }}
