minikube-ip: 192.168.64.13

eddy-kafka-graphql-bridge:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - subscriptions.192.168.64.13.nip.io

eddy-automl-backend:
  allowedHosts: localhost,192.168.64.13,api.192.168.64.13.nip.io,automl-ui.192.168.64.13.nip.io
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - api.192.168.64.13.nip.io

eddy-automl-ui:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - automl-ui.192.168.64.13.nip.io
  config_json:
    {
      "debug": false,
      "dataGraphQLClient": {
        "httpEndpoint": "http://api.192.168.64.13.nip.io/api/graphql",
        "wsEndpoint": "ws://subscriptions.192.168.64.13.nip.io/subscriptions"
      }
    }
