kafka:
  enabled: false

eddy-kafka-graphql-bridge:
  # Use the existing Kafka cluster service name from the strimzi-kafka-operator namespace
  kafkaBootstrapServer: 'my-cluster-kafka-bootstrap.strimzi-kafka-operator.svc.cluster.local:9092'
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - eddy-automl-subscriptions.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-subscriptions-tls
        hosts:
          - eddy-automl-subscriptions.k.eddy-analytics.org

eddy-automl-backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - eddy-automl-backend.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-backend-tls
        hosts:
          - eddy-automl-backend.k.eddy-analytics.org

eddy-automl-ui:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - automl.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-ui-tls
        hosts:
          - automl.k.eddy-analytics.org
  config_json:
    {
      "debug": false,
      "dataGraphQLClient": {
        "httpEndpoint": "https://eddy-automl-backend.k.eddy-analytics.org/api/graphql",
        "wsEndpoint": "wss://eddy-automl-subscriptions.k.eddy-analytics.org/subscriptions"
      }
    }
