eddy-kafka-graphql-bridge:
  service:
    type: NodePort
    port: 8090

eddy-automl-backend:
  allowedHosts: '*'
  service:
    type: NodePort
    port: 8000

eddy-automl-ui:
  service:
    type: NodePort
    port: 80
  config_json:
    {
      "debug": false,
      "dataGraphQLClient": {
        "httpEndpoint": "http://192.168.64.9:30741",
        "wsEndpoint": "ws://192.168.64.9:32338 "
      }
    }
