# the database that the eddy-automl-backend uses
mysql:
  # https://github.com/helm/charts/tree/master/stable/mysql
  enabled: true
  mysqlDatabase: eddy-automl-backend
  mysqlUser: eddy-automl-user
  mysqlPassword: secure-mysql-password

kafka:
  enabled: true

eddy-kafka-graphql-bridge:
  ingress:
    enabled: false
  kafkaBootstrapServer: '{{ .Release.Name }}-kafka:9092'

eddy-automl-backend:
  debug: 'True'
  jobsNamespace: eddy-automl-jobs
  kafkaBootstrapServer: '{{ .Release.Name }}-kafka.{{ .Release.Namespace }}:9092'
  ingress:
    enabled: false
  dbName: eddy-automl-backend
  dbUser: eddy-automl-user
  dbPass: secure-mysql-password
  dbHost: '{{ .Release.Name }}-mysql'
  dbPort: 3306

eddy-automl-ui:
  ingress:
    enabled: false
  config_json:
    {
      "debug": false,
      "dataGraphQLClient": {
        "httpEndpoint": "https://",
        "wsEndpoint": "wss://"
      }
    }

demoDataJob:
  enabled: true
  kafkaBootstrapServer: '{{ .Release.Name }}-kafka:9092'