kafka:
  enabled: false

eddy-kafka-graphql-bridge:
  # Annotate the deployment with keel (pull the latest docker image) and reloader (reload on ConfigMap changes)
  annotations:
    keel.sh/match-tag: "true"
    keel.sh/policy: force
    reloader.stakater.com/auto: "true"
  # Use the existing Kafka cluster service name from the strimzi-kafka-operator namespace
  kafkaBootstrapServer: 'my-cluster-kafka-bootstrap.strimzi-kafka-operator.svc.cluster.local:9092'
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - eddy-automl-subscriptions.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-subscriptions-tls
        hosts:
          - eddy-automl-subscriptions.k.eddy-analytics.org

eddy-automl-backend:
  allowedHosts: localhost,127.0.0.1,automl.k.eddy-analytics.org
  jobsNamespace: eddy-automl-jobs
  kafkaBootstrapServer: 'my-cluster-kafka-bootstrap.strimzi-kafka-operator.svc.cluster.local:9092'
  # Annotate the deployment with keel (pull the latest docker image) and reloader (reload on ConfigMap changes)
  annotations:
      keel.sh/match-tag: "true"
      keel.sh/policy: force
      reloader.stakater.com/auto: "true"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - eddy-automl-backend.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-backend-tls
        hosts:
          - eddy-automl-backend.k.eddy-analytics.org

eddy-automl-ui:
  # Annotate the deployment with keel (pull the latest docker image) and reloader (reload on ConfigMap changes)
  annotations:
      keel.sh/match-tag: "true"
      keel.sh/policy: force
      reloader.stakater.com/auto: "true"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - automl.k.eddy-analytics.org
    tls:
      - secretName: eddy-automl-ui-tls
        hosts:
          - automl.k.eddy-analytics.org
  config_json:
    {
      "debug": false,
      "dataGraphQLClient": {
        "httpEndpoint": "https://eddy-automl-backend.k.eddy-analytics.org/api/graphql",
        "wsEndpoint": "wss://eddy-automl-subscriptions.k.eddy-analytics.org/subscriptions"
      }
    }

demoDataJob:
  enabled: true
  kafkaBootstrapServer: 'my-cluster-kafka-bootstrap.strimzi-kafka-operator.svc.cluster.local:9092'