config_json:
  {
    "debug": false
  }

replicaCount: 1

image:
  repository: eddyanalytics/eddy-automl-ui
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80


nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}
podAnnotations: {}
